### ISSUE TITLE
View Statistic not working and few more feature request

### ISSUE THREAD

**Issue by bkrajendra** [gergo85/oc-news#10]
@gergo85  View statistics still not working after updating.
Also it will be nice if
1) front end users can be part of subscribers
2) Bulk import of subscribers through text or excel file.

**Comment by gergo85** [comment]
I tried the statistic and it works properly for me. My post page is:
![stat](https://cloud.githubusercontent.com/assets/2959112/11093599/6d82d2f6-888b-11e5-98b3-0dc834a437aa.jpg)

Thank you for your ideas.

**Comment by bkrajendra** [comment]
@gergo85 
I don't know how your statistics component is working. If you take look at you componenet file (components/stat/default.html), its empty. Make sure you have synced latest changes to Git.
Following changes are needed.
in components/Stat.php
```php
    public function onRun()
    {
        $stat = DB::table('news_posts')->where('slug', $this->param('slug'))->pluck('statistics');
        DB::table('news_posts')->where('slug', $this->param('slug'))->update(array('statistics' => ++$stat));

		$this->stats = $this->page['stats'] = $stat; //Added this line
    }
```

And in components/stat/default.html
```html
Viewed {{ stats }} times
```

**Comment by gergo85** [comment]
The post view statistics is now automatic. Please update the plugin.
