### ISSUE TITLE
Issues with SEO commit examples

### ISSUE THREAD

**Issue by Gamertech** [gergo85/oc-news#100]
Been looking into your new SEO tag option and noticed a couple of issues with your examples in https://github.com/gergo85/oc-news/commit/b21cedb4467cd1966fb218ad3e288b9cd579d0f1 .

- title is not a W3C-recognised value for the meta tag, and is mostly ignored by search engines. Page titles should be in <title> tags to be recognised.

Using your example, it should be:

`<title>{% if post.seo_title %}{{ post.seo_title }}{% elseif this.page.meta_title %}{{ this.page.meta_title }}{% else %}{{ this.page.title }}{% endif %}</title>`

- Also, use of the meta=keywords value has long since been considered as a spam signal.

Even though it's still a W3C-approved value, Google, Baidu, Yandex etc ignore it while Bing actively penalises websites for using it as even today people still use it in an attempt to impact SEO by keyword-stuffing.

**Comment by gergo85** [comment]
Thank you for your suggestions! I modified the documentation.
