### ISSUE TITLE
ERROR after update "Added SEO fields to news". Unknown column 'seo_desc' in 'field list'

### ISSUE THREAD

**Issue by plyusninva** [gergo85/oc-news#102]
after the last update, an error occurs while creating the news
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'seo_desc' in 'field list' (SQL: insert into `indikator_news_posts` (`user_id`, `title`, `slug`, `introductory`, `content`, `seo_desc`, `seo_title`, `seo_keywords`, `seo_image`, `image`, `published_at`, `status`, `featured`, `category_id`, `tags`, `updated_at`, `created_at`) values (...

**Comment by gergo85** [comment]
I fixed this issue. Please update the plugin!
