### ISSUE TITLE
Filter next and previous button with category

### ISSUE THREAD

**Issue by jonnydevv** [gergo85/oc-news#106]
Hello,

Previous and next button inside post isn't filtering with category used in post.list.
Example:
`{% if post.next().title %}Next: <a href="{{ 'news-article'|page({ slug: post.next().slug }) }}" class="next">{{ post.next().title }}</a>{% endif %}`
This links sends me to next plublished post without category filtered.
Maybe adding a category parameter to component _post_ would help.
This way we could use:
`{% if post.next().title %}Next: <a href="{{ 'news-article'|page({ slug: post.next().slug, category: 'sports' }) }}" class="next">{{ post.next().title }}</a>{% endif %}`

If I'm missing something to filter next and previous post inside categories, some help would be nice.

Thanks in advance

**Comment by TimFoerster** [comment]
@jonnydevv Plugin now supports `next` and `prev` post.

```
{% if __SELF__.prev %}Prev: <a href="{{ __SELF__.prev.url }}" class="prev">{{ __SELF__.prev.title }}</a>{% endif %}
```
