### ISSUE TITLE
There should be some link to "unsubscribe" in every email that is sent!

### ISSUE THREAD

**Issue by bkrajendra** [gergo85/oc-news#11]
Hi @gergo85 can you add unsubscribe facility for subscriber.
Either from front end or there should be link at the bottom of each email sent to subscriber.

**Comment by gergo85** [comment]
Thank you for your idea. Perhaps I will make it.

**Comment by bkrajendra** [comment]
@gergo85 
I have resolved the Unsubscribe issue by using MailGun.
I'll alway suggest using bulk mail provider as email driver as gmail/SMTP gets exhausted if number subscriber are even more than 200 (as on my shared server, i could not send news to bulk users.)

Hence i choose MailGun as my Email Driver (Email Method). 
Make sure to enable Unsubscribe in Domain setting. This will automatically append Unsubscribe link to every outgoing email.
Also enable tracking for more Insights.

For Unsubscribe Action. Ive created Webhook in MailGun control Panel.
Webhook requires web URL.

So I created new page in october CMS with following code:
http://mydomain.com/news/unsubscribe

put this in Marku section:(optional)
```
result:{{resp}}
```

put this in  code section 
```php
function onStart()
{
   //Parameter sent by MailGun WebHook
    $timestamp = post('timestamp');
    $token = post('token');
    $signature = post('signature');
    $recipient = post('recipient');
    
   //Compute HMAC - required by MailGun for request verification.
    $cmputed = hash_hmac('SHA256', $timestamp.$token, 'MAILGUN_API_KEY');

    //Compare - verify validity
    if ($cmputed == $signature)
    {
        //Delete selected recipient email from database.
        $resp = DB::table('news_subscribers')->where('email', $recipient)->delete();
        $this["resp"] = $recipient.','.$resp;  
    }else
    {
        //Invalid Request
        $this["resp"] = $recipient.', invalidrequest';
    }
}
```

Then finally added this webhook URL in MailGun control panel Webhook section's "Unsubscribes webhook".

Yet I've not actually tested by clicking on Unsubscribe button in Email but I think theoretically its correct.

**Comment by gergo85** [comment]
The unsubscribe front-end component is available. Please update the plugin.
