### ISSUE TITLE
Memory limit config

### ISSUE THREAD

**Issue by JanHerman87** [gergo85/oc-news#119]
Hi, would it be possible to add option where we could specify memory limit for queue command?
Something like this:

_queue:work --daemon --queue=newsletter --memory=256_

The default 128 is not big enough for us, and its not very easy to override this.

Should be really easy fix, I already did it, but I cant push to remote.

**Comment by TimFoerster** [comment]
Fork the project and submit a pull request

**Comment by JanHerman87** [comment]
@TimFoerster done.
