### ISSUE TITLE
Updating news item in plain-text mode doesn't work

### ISSUE THREAD

**Issue by eXpl0it3r** [gergo85/oc-news#12]
**Steps to reproduce**
* Open an existing news item
* Switch to plain-text mode
* Edit the code (e.g. add a `<p>` tag)
* Click `Save` (you'll get a nice notification that it got saved)
* Refresh the news list
* Change has not been applied

**Workaround**
Before saving the edited code, switch back to the rich-text view and then click save.

**Cause**
I'm not familiar with the code, so I've no idea. JavaScript console stays clean so it doesn't seem like some JavaScript command went wrong.

**Comment by gergo85** [comment]
Thank you for reporting this issue. This is the editor's problem.
