### ISSUE TITLE
Error displaying post

### ISSUE THREAD

**Issue by Ch-ek** [gergo85/oc-news#128]
Good afternoon, I have not updated the plugin for a long time and yesterday I updated it. I got an error.
![error plugin news newsletter](https://user-images.githubusercontent.com/40349451/77156222-c46d8b80-6ac0-11ea-8492-fce88f084910.png)

In the settings of the plugin SEO-settings, tags and categories are disabled and they will not be included

Сan put a check for the existence of $post-> category->name before line 79

**Comment by gergo85** [comment]
Thank you for report this error. I fixed it. Please update the plugin!
