### ISSUE TITLE
Multiple categories

### ISSUE THREAD

**Issue by helmutkaufmann** [gergo85/oc-news#129]
Great plugin. Any chance to support the selection of multiple categories per post or - altermatively - how would I select select all post belonging to a list of categories (what I want to do is to display an ordered list of posts belonging to different categories).

_Originally posted by @helmutkaufmann in https://github.com/gergo85/oc-news/issues/23#issuecomment-602023797_

**Comment by gergo85** [comment]
I added this feature to my todo list.

**Comment by TimFoerster** [comment]
@gergo85 do you had any progress? Otherwise I will do it tomorrow.

**Comment by gergo85** [comment]
@TimFoerster I haven't started yet. Thank you very much the contribution!

**Comment by gergo85** [comment]
@helmutkaufmann Multiple categories feature has been added.
