### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by feitzi** [gergo85/oc-news#13]
I use your plugin for my website to show some news on the landing page. 
But i have some problems with the translation of the plugin. The problem is that translation isn't working. No matter what language is selected the news are displayed in the main language. 
Every other plugin works fine with translation.

I changed the content for every language with this translation icon:  

![image](https://cloud.githubusercontent.com/assets/2361489/13121622/549af280-d5b3-11e5-9a59-71902ce2b361.png)

October Build: 316  
Version of OC-news: 1.3.9

**Comment by gergo85** [comment]
Do you use the default front-end component or own code to display the posts?

**Comment by feitzi** [comment]
I use the default post-list component.

![image](https://cloud.githubusercontent.com/assets/2361489/13612674/f55ce632-e568-11e5-90db-900dcce6a8c8.png)

**Comment by feitzi** [comment]
Any ideas how i can fix this?

**Comment by gergo85** [comment]
I am working on the problem.

**Comment by gergo85** [comment]
If it is urgent, use this following code. I know, it isn't the best solution, but it works. I don't understand while the Rainlab Translation plugin doesn't work properly.

HTML code
``
<ul class="post-list">
    {{ list|raw }}
</ul>
``

PHP code
``
function onStart()
{
    $this['list'] = 'dadasdas';
    $sql = DB::table('news_posts')->where('status', 1)->orderBy('published_at', 'desc')->get();

    foreach ($sql as $post) {
        if (Schema::hasTable('rainlab_translate_attributes')) {
            $translate = json_decode(DB::table('rainlab_translate_attributes')->where('locale', App::getLocale())->where('model_id', $post->id)->where('model_type', 'Indikator\News\Models\Posts')->pluck('attribute_data'), true);

            if ($translate['title'] != '') {
                $post->title = $translate['title'];
            }
            if ($translate['introductory'] != '') {
                $post->introductory = $translate['introductory'];
            }
            if ($translate['content'] != '') {
                $post->content = $translate['content'];
            }
        }

        $this['list'] .= '
        <li>
            <img src="/storage/app/media'.$post->image.'" alt="'.$post->title.'">
            <h3><a href="news/post/'.$post->slug.'">'.$post->title.'</a></h3>
            <p class="date">'.$post->published_at.'</p>
            <p class="introductory">'.$post->introductory.'</p>
        </li>';
    }
}
``

**Comment by feitzi** [comment]
Hy @gergo85 

with version 1.4 everythins works smoothly. 
thank you
