### ISSUE TITLE
Sending News through the queue work with connection type database

### ISSUE THREAD

**Issue by igor-tv** [gergo85/oc-news#132]
I need help. I am trying to set up the News sending queue. 

I did in the config QUEUE_DRIVER=database, then launched daemon queue worker via command line `php artisan queue:work database`.  When I send a newsletter, letters remain in the queue, but are not sent. Entries are created in the jobs table in the database.

<img width="988" alt="Снимок экрана 2020-03-31 в 03 27 58" src="https://user-images.githubusercontent.com/6777469/77974403-b78e3a80-72ff-11ea-94dd-5d6169d7de1f.png">

Rebooting workers does not give a result.

I use Mailgun to send letters. With standard `sync` queue sending emails works, but when sending a letter to a large number of subscribers, there is not enough time to execute the script and it takes 20+ letters.

Am I missing any additional settings, or is this a plugin bug?

**Comment by TimFoerster** [comment]
Because you need to set the queue name
`php artisan queue:work --queue=newsletter`
