### ISSUE TITLE
Send mails in paralel

### ISSUE THREAD

**Issue by lfcc1** [gergo85/oc-news#148]
Hello
I have 900 emails thus I'm sending 900 emails each time.
This process takes time and my server is only able to take requests 300 seconds max, which results in a 504 or 502 error.
Is it possible to send the emails in parallel?

**Comment by TimFoerster** [comment]
Use an async driver.

**Comment by lfcc1** [comment]
Ok I changed my driver to database but now all my emails are just queued and not sent.
I tried to read https://laravel.com/docs/8.x/queues but I was not able to make it work.

Im find the october cms documentation very poor. Is there any documentation so I can understand how to configure or make this new driver work?

**Comment by TimFoerster** [comment]
You can use the scheduler
https://octobercms.com/docs/setup/installation#crontab-setup
 
or can run the queue handler with
`queue:work --daemon --queue=newsletter`
documented here:
https://octobercms.com/docs/services/queues#running-the-queue-worker

**Comment by lfcc1** [comment]
First of all, thank you for the explanation, it was really helpful.

However, I faced a problem with the scheduler.
When I run it manually with `php artisan scheduler:run` and then close it with CTRL + C, if I try to start it again it will return  `No scheduled commands are ready to run`

After a little debugging I found out it was the `->withoutOverlapping();` that was causing the problem. In order for it to work again I had to clean the php artisan cache with `php artisan cache:clear`.

So I'm assuming that the cronjob is never-ending, and if it ends, it will not start again until the php artisan cache is cleared.
Am I doing this right?

**Comment by TimFoerster** [comment]
If you execute `crontab -e` you can enter `* * * * * php /path/to/your/artisan schedule:run >> /dev/null 2>&1` and it should run as expected (1 mail per minute). Nothing else is needed.

**Comment by nolyboms** [comment]
So in order to make queued mail sending to work the driver needs to be set to "database" ?

**Comment by TimFoerster** [comment]
you could use everything, except `synchronous` and `null`, depending on your environment
