### ISSUE TITLE
Class 'Jenssegers\Date\Date' not found

### ISSUE THREAD

**Issue by nolyboms** [gergo85/oc-news#149]
Getting error when clicking on the opt-in mail "confirm your email":

Class 'Jenssegers\Date\Date' not found

Here (https://octobercms.com/support/article/RN-11) it says ...

"The jenssegers/date library has been removed from October entirely as most of its functionality is now present in Carbon 2.0. This should mostly work with existing code unless you were referencing it directly, in which case replace any references to Jenssegers\Date\Date with October\Rain\Argon\Date."

How to fix please?

**Comment by TimFoerster** [comment]
Feel free to submit a PR.

**Comment by gergo85** [comment]
I removed the Jenssegers\Date\Date dependence. Please test it.

**Comment by nolyboms** [comment]
Downloaded from marketplace and still got same errors.

My fix is..

- replace "use Jenssegers\Date\Date;" with  "use Carbon\Carbon;"
- replace "Date::" with "Carbon::"

**Comment by TimFoerster** [comment]
@nolyboms  "testing" does not mean to download from marketplace. Use git instead.

**Comment by nolyboms** [comment]
Be nice to newbies @TimFoerster...still learning every day. Just saw the commit i was supposed to use. 

Thank you @gergo85!

**Comment by TimFoerster** [comment]
@nolyboms sorry, i deleted the commet.
