### ISSUE TITLE
Fork for winterCMS

### ISSUE THREAD

**Issue by Fenn-CS** [gergo85/oc-news#150]
Hi @gergo85 sure you are aware about the updates on octobercms/wintercms what do you think about a winter fork? 
I don't mind doing the fork but perhaps you considered?

**Comment by nolyboms** [comment]
Tested on winter cms and it works with @gergo85 commit:

https://github.com/gergo85/oc-news/commit/d921795b88685dc89f1ac2e4c6c790d1844867df

**Comment by Fenn-CS** [comment]
@nolyboms sure it would work, but WinterCMS has specification on how to publish plugins on packagist so they can be installed with composer, so that's the install mechanism I was looking at here.
