### ISSUE TITLE
BadMethodCallException: Method join does not exist

### ISSUE THREAD

**Issue by snipiba** [gergo85/oc-news#162]
From stack:
. in /vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:96

called by :
plugins/indikator/news/models/posts/_categories.htm(3): Illuminate\Support\Collection->__call('join', Array)

**Comment by AT-Mneme** [comment]
I am having similar issue BadMethodCallException: Method join does not exist but from stack:
/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php line 96

everything works ok but when I tapped the menu bar on Newsletter on backend, the above error appears. 
This error appeared after I had updated 1.12.1 version of the plugin.

**Comment by TimFoerster** [comment]
Please provide PHP and OCMS version

**Comment by AT-Mneme** [comment]
> Please provide PHP and OCMS version

PHP 7.4.3, OCMS version OCMS version 476.

**Comment by snipiba** [comment]
> Please provide PHP and OCMS version

mine OCMS 476 too, News plugin at v. 1.12.1

**Comment by AT-Mneme** [comment]
So I just added the code below at the _categories.htm will solve badmethodcallexception? Or I have to backward the compatibility to larval 5.5.x? 
echo str_limit(implode(', ',$record->categories->pluck('name')->toArray()), 30);

added the code to update categories still the error still exists.
