### ISSUE TITLE
BadMethodCallException: Call to undefined method Illuminate\Mail\Message::getSwiftMessage() in C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Support\Traits\ForwardsCalls.php:71

### ISSUE THREAD

**Issue by ARIFCAHYO09** [gergo85/oc-news#172]
BadMethodCallException: Call to undefined method Illuminate\Mail\Message::getSwiftMessage() in C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Support\Traits\ForwardsCalls.php:71
Stack trace:
#0 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Support\Traits\ForwardsCalls.php(36): Illuminate\Mail\Message::throwBadMethodCallException('getSwiftMessage')
#1 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Support\Traits\ForwardsCalls.php(52): Illuminate\Mail\Message->forwardCallTo(Object(Symfony\Component\Mime\Email), 'getSwiftMessage', Array)
#2 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Mail\Message.php(400): Illuminate\Mail\Message->forwardDecoratedCallTo(Object(Symfony\Component\Mime\Email), 'getSwiftMessage', Array)
#3 C:\xampp\htdocs\october\plugins\indikator\news\classes\SendNews.php(59): Illuminate\Mail\Message->__call('getSwiftMessage', Array)
#4 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(421): Indikator\News\Classes\SendNews::Indikator\News\Classes\{closure}(Object(October\Rain\Mail\Mailer), 'indikator.news:...', Object(Illuminate\Mail\Message))
#5 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('mailer.prepareS...', Array)
#6 C:\xampp\htdocs\october\vendor\october\rain\src\Events\PriorityDispatcher.php(94): Illuminate\Events\Dispatcher->dispatch('mailer.prepareS...', Array, true)
#7 C:\xampp\htdocs\october\vendor\october\rain\src\Events\PriorityDispatcher.php(61): October\Rain\Events\PriorityDispatcher->fireEvent('mailer.prepareS...', Array, true)
#8 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(338): October\Rain\Events\PriorityDispatcher->fire('mailer.prepareS...', Array, true)
#9 C:\xampp\htdocs\october\vendor\october\rain\src\Mail\Mailer.php(113): Illuminate\Support\Facades\Facade::__callStatic('fire', Array)
#10 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Mail\Mailable.php(211): October\Rain\Mail\Mailer->send('indikator.news:...', Array, Object(Closure))
#11 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Support\Traits\Localizable.php(19): Illuminate\Mail\Mailable->Illuminate\Mail\{closure}()
#12 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Mail\Mailable.php(212): Illuminate\Mail\Mailable->withLocale(NULL, Object(Closure))
#13 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php(307): Illuminate\Mail\Mailable->send(Object(October\Rain\Mail\Mailer))
#14 C:\xampp\htdocs\october\vendor\october\rain\src\Mail\Mailer.php(60): Illuminate\Mail\Mailer->sendMailable(Object(Indikator\News\Classes\NewsletterMail))
#15 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Mail\MailManager.php(505): October\Rain\Mail\Mailer->send(Object(Indikator\News\Classes\NewsletterMail))
#16 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(338): Illuminate\Mail\MailManager->__call('send', Array)
#17 C:\xampp\htdocs\october\plugins\indikator\news\classes\SendNews.php(133): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#18 C:\xampp\htdocs\october\plugins\indikator\news\classes\SendNews.php(105): Indikator\News\Classes\SendNews::send('indikator.news:...', Array, Array, 'tes')
#19 C:\xampp\htdocs\october\plugins\indikator\news\classes\SendNews.php(35): Indikator\News\Classes\SendNews::sendWithLogger('indikator.news:...', Array, Array, 'tes', Object(Indikator\News\Models\Logs))
#20 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Queue\Jobs\Job.php(98): Indikator\News\Classes\SendNews->fire(Object(Illuminate\Queue\Jobs\SyncJob), Array)
#21 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Queue\SyncQueue.php(43): Illuminate\Queue\Jobs\Job->fire()
#22 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Queue\QueueManager.php(291): Illuminate\Queue\SyncQueue->push('\\Indikator\\News...', Array, 'newsletter')
#23 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(338): Illuminate\Queue\QueueManager->__call('push', Array)
#24 C:\xampp\htdocs\october\plugins\indikator\news\classes\NewsSender.php(255): Illuminate\Support\Facades\Facade::__callStatic('push', Array)
#25 C:\xampp\htdocs\october\plugins\indikator\news\classes\NewsSender.php(132): Indikator\News\Classes\NewsSender->send(Object(Indikator\News\Models\Subscribers))
#26 C:\xampp\htdocs\october\plugins\indikator\news\classes\NewsSender.php(96): Indikator\News\Classes\NewsSender->sendToActiveSubscribers()
#27 C:\xampp\htdocs\october\plugins\indikator\news\controllers\Posts.php(78): Indikator\News\Classes\NewsSender->sendNewsletter()
#28 C:\xampp\htdocs\october\modules\system\traits\DependencyMaker.php(29): Indikator\News\Controllers\Posts->onNewsSend('1')
#29 C:\xampp\htdocs\october\modules\backend\classes\Controller.php(602): Backend\Classes\Controller->makeCallMethod(Object(Indikator\News\Controllers\Posts), 'onNewsSend', Array)
#30 C:\xampp\htdocs\october\modules\backend\classes\Controller.php(447): Backend\Classes\Controller->runAjaxHandler('onNewsSend')
#31 C:\xampp\htdocs\october\modules\backend\classes\Controller.php(256): Backend\Classes\Controller->execAjaxHandlers()
#32 C:\xampp\htdocs\october\modules\backend\classes\BackendController.php(127): Backend\Classes\Controller->run('update', Array)
#33 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): Backend\Classes\BackendController->run('indikator/news/...')
#34 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction('run', Array)
#35 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\Route.php(260): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Backend\Classes\BackendController), 'run')
#36 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\Route.php(205): Illuminate\Routing\Route->runController()
#37 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\Router.php(727): Illuminate\Routing\Route->run()
#38 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#45 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\Router.php(728): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#52 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\Router.php(705): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#53 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\Router.php(669): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#54 C:\xampp\htdocs\october\vendor\october\rain\src\Router\CoreRouter.php(32): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#55 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(190): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#56 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#57 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 C:\xampp\htdocs\october\vendor\october\rain\src\Foundation\Http\Middleware\CheckForMaintenanceMode.php(23): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(165): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#62 C:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#63 C:\xampp\htdocs\october\index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#64 {main}

**Comment by gergo85** [comment]
What is the version of your October CMS?

**Comment by ARIFCAHYO09** [comment]
3 php 8.0

**Comment by gergo85** [comment]
Thanks for the information! For now this plugin not support the October v3.x.

The October 3 uses Symfony Mailer instead of SwiftMailer. This is the reason why sending feature does not work.
