### ISSUE TITLE
Pagination not working

### ISSUE THREAD

**Issue by eXpl0it3r** [gergo85/oc-news#18]
I've recently noticed that the pagination as provided [by the default posts component](https://github.com/gergo85/oc-news/blob/master/components/posts/default.htm#L21) doesn't work (anymore?). I just copy and pasted that into my partial page.
The pagination boxes seem to be generated correctly, however the links are just pointing to the root of the website.

![](http://i.imgur.com/yah4shf.png)

Am I doing something wrong or is this indeed broken?

**Comment by gergo85** [comment]
I am looking for the solution, but I didn't find it yet.

**Comment by gergo85** [comment]
I fixed this issue. Please update the plugin for latest version.

**Comment by eXpl0it3r** [comment]
Seems to work nicely. Thanks!
