### ISSUE TITLE
Translate plugin conflict

### ISSUE THREAD

**Issue by vdomah** [gergo85/oc-news#19]
Hello!

this code in Posts model causes error in Translate plugin:

`public $translatable = [
        'title',
        ['slug', 'index' => true],
        'introductory',
        'content'
    ];`

because you use  ['slug', 'index' => true] translate/Plugin.php gets error on line 237 trying to flip array

`$translatable = array_flip($model->translatable);`

I just commented ['slug', 'index' => true], because I don't need different slugs for languages

**Comment by gergo85** [comment]
Is this error still available?
