### ISSUE TITLE
Support for categories

### ISSUE THREAD

**Issue by martinBadin** [gergo85/oc-news#23]
Hi,

please, can you add support for categories? Thank you

**Comment by gergo85** [comment]
Hi,
This is a simple news plugin so I don't plan to extend with categories. If I have a lot of free time, I will do it.

**Comment by matteotrubini** [comment]
Would you accept a PR about that? It's a missing feature on a project that I'm developing, so I can contribute instead of maintain a fork.

**Comment by gergo85** [comment]
Thank you for your offering! I have already made this feature. Please update the plugin to latest version.

**Comment by helmutkaufmann** [comment]
Great plugin. Any chance to support the selection of multiple categories per post or - altermatively - how would I select select all post belonging to a list of categories (what I want to do is to display an ordered list of posts belonging to different categories).
