### ISSUE TITLE
Multilanguage Newsletter

### ISSUE THREAD

**Issue by m-paniez9292** [gergo85/oc-news#24]
Hi,
I would like to make a multilanguage newsletter.
So, in the plugin, all seems ok but how can I use a specific mail template (I create a new template with the right language code - ie indikator.news::mail.email_fr like your indikator.news::mail.email_en - , but it's not working).
Thanks

**Comment by gergo85** [comment]
Hi,
I modified the sending code. Please update the plugin. It is work?

**Comment by m-paniez9292** [comment]
Re,
Nothing change for selecting the right template : is it automatic or manual, in the news "post" (the content is in french) ?

Thanks

**Comment by gergo85** [comment]
I am working on this issue. I will update the plugin as soon as.

**Comment by gergo85** [comment]
I updated the plugin with the multilingual subscription feature.
