### ISSUE TITLE
Email was send ?

### ISSUE THREAD

**Issue by m-paniez9292** [gergo85/oc-news#27]
Hi,

In your plugin, by default, in a new post, "sending email" button is on and "published" button is selected. If I save the post, email(s) was/were sent ?

Because, in subscribers, in the "sent" column, I have always "0". So, how can I will be sure if email was sent ?

Thanks

**Comment by gergo85** [comment]
Hi,

If you click on the Send test message button, do you get a mail?

**Comment by m-paniez9292** [comment]
Re,

Yes, all works great with that (with template test and post test) and link generation is ok.

Just, we are edited a post, we save it and some subscribers receive it without change something (we don't know how many) ; in subscribers menu, the "sent" column stay at "0" (I verifiy in DB and it's the same value).

We changed your default settings for a post : we put "send" at false and "published" at "2" (for draft).

So, is it a way to know if email was sent or a report with all sending email ?

Thanks

**Comment by m-paniez9292** [comment]
Re,

Thanks for this plugin (very usefull).

So, when a post has "send button" at on and we modify it, posts are re-send.

So, I think, by default, this button will be at off and post state at draft (my conclusions) ; like that, we can control sending posts.

Thanks

**Comment by gergo85** [comment]
Hi,

I see the problem. I changed the default value of sending checkbox to off.
Please update the plugin. I hope it will be solved the re-send issue.

Regards,
Gergo



2017-07-04 10:01 GMT+02:00 m-paniez9292 <notifications@github.com>:

**Comment by TimFoerster** [comment]
I have problems with the resend issue.

When the checkbox is checked, it'll always resends the newsletter.
How about creating a button instead of a checkbox? That should be much safer.
