### ISSUE TITLE
more detailed logs

### ISSUE THREAD

**Issue by TimFoerster** [gergo85/oc-news#33]
Hey

I plan to create a more detailed log that shows the status of the email sending (queued/sending/sent/viewed/link clicked).

Any suggestion? I try to give you a PR.

**Comment by gergo85** [comment]
Big thanks for this new feature. I will test it.

**Comment by TimFoerster** [comment]
okay, if you have some questions, feel free to ask me.

**Comment by gergo85** [comment]
I updated the plugin. Thanks again to the new features.

**Comment by TimFoerster** [comment]
Good changes, thank you for reviewing.
