### ISSUE TITLE
error when I try to install

### ISSUE THREAD

**Issue by jodumont** [gergo85/oc-news#41]
Hi;

I found your plugins in the marketplace and when I try to install it I got this error :

> PDOException: SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "statistics" cannot be cast automatically to type integer
> 
> HINT:  You might need to specify "USING statistics::integer". in /config/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105
> 

Now this is my config:

System build: 431
I use October with Nginx + Posgres 10

I hope these info are usefull for you :)

Regards!!

Jonathan

**Comment by gergo85** [comment]
I updated the plugin! Please try it again.
