### ISSUE TITLE
make the plugin GDPR conform

### ISSUE THREAD

**Issue by TimFoerster** [gergo85/oc-news#48]
Hey Szabó,

I want to make this plugin GDPR conform. 
Things to do:

- [x] Extend subscriber model
- [x] Double Opt-In for new subscribers
- [x] Store newsletter subscribing timestamp + IP address
- [x] Create Opt-In confirmation link
- [x] Send Opt-In newsletter confirmation
- [ ] Store newsletter subscribing confirmation timestamp + IP address

My plan is to store those timestamps into the subscriber model. Fields to add: (`registered_at`, `registered_ip`, `confirmed_at`, `confirmed_ip`, `unsubscribed_at`, `unsubscribed_ip`).

Any suggestions?

**Comment by gergo85** [comment]
Hi,

There is a good idea. Now I have no other suggestions.

**Comment by TimFoerster** [comment]
I'll try to Start ist the upcoming days.
