### ISSUE TITLE
Problem with cronjob

### ISSUE THREAD

**Issue by LarBearrr** [gergo85/oc-news#49]
I know this may be slightly off topic, but I am having problems with the queue. When I first add my cron job, it seems to work fine. However, subsequent calls produce this error:

![image](https://user-images.githubusercontent.com/28734844/39152757-e5470bb0-470e-11e8-8150-76e2fc87b832.png)

Any help would be appreciated. Thank you :)

**Comment by TimFoerster** [comment]
Did you set up the cron job with the correct user? You can't open the log file because the cron User does not have the rights for it

**Comment by TimFoerster** [comment]
I dont specified an output. On my production I run `cd /ROOT/PROJECT/PATH && php7.1-cli artisan queue:work --queue=newsletter --once`. Make sure that you run the code with the correct php version. Maybe cli helps you also out. Don't define the driver in the cron job, use configs for that. Maybe changing into that directory also helps.

**Comment by TimFoerster** [comment]
@WWRFresource does it worked out for you?

**Comment by WWRFresource** [comment]
@TimFoerster Thanks for checking in with me. I still haven't been able to get the cronjob to run properly. I am just manually running the job each time I want to send out a newsletter. I'd like to get it straightened out if you have time to help me.
