### ISSUE TITLE
how can i display post category ?

### ISSUE THREAD

**Issue by ajmanco** [gergo85/oc-news#56]
I have a simple issue but cant find any solutions . i want to display a category that post are into .
i use `{{ post.category }}`  but it wont work and shows a row af sql log  like this : 
`
{"id":1,"name":"New Category","slug":"new-category","content":"<p>test content<\/p>","image":"","hidden":"2","status":"1","sort_order":"1","created_at":"2018-01-27 18:24:29","updated_at":"2018-01-27 18:24:29"}`
What can i do to display my post category in post page ?

**Comment by ajmanco** [comment]
any answere ?

**Comment by gergo85** [comment]
I made it. Please update the plugin from Github or force update to your website.

You can use the following variables:

```
ID: post.category.id
Name: post.category.name
Slug: post.category.slug
Content: post.category.content|raw
Image: post.category.image
```
