### ISSUE TITLE
Twig filter "_" does not exist

### ISSUE THREAD

**Issue by initbiz** [gergo85/oc-news#6]
Hi,
I wanted to add posts list to my page and got "Exception" page:
The filter "_" does not exist. Did you mean "url_encode", "json_encode", "date_modify", "number_format", "convert_encoding"

in (...)/plugins/indikator/news/components/posts/default.htm line 24.

After I removed _ filter from Prev and Next in default.html file, component managed to work. I do not undestand Twig yet so everything I can do now is to inform you about the problem.

**Comment by gergo85** [comment]
Thank you for reporting this issue. I fixed it.
