### ISSUE TITLE
Incorrect integer value for column 'job_id'

### ISSUE THREAD

**Issue by tanyiknie** [gergo85/oc-news#61]
Hi, I have encountered an error during sending the newsletter post. Below is the logged info:

PDOException: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'J1So6ywpZLWphxeeRwVbHfV3h8hK7AfS' for column 'job_id' at row 1 in /apps/xxxx/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105

I checked the database table for column "job_id", the current type is "int(10)". Should it be "varchar(255)" type instead?

**Comment by TimFoerster** [comment]
oh no, what ocms build do you use?
Didn't noticed that the job id type has changed

**Comment by TimFoerster** [comment]
what is your queue driver?

**Comment by tanyiknie** [comment]
@TimFoerster , the info as below:
ocms build: 430
QUEUE_DRIVER=redis
