### ISSUE TITLE
Publish status and date coherence

### ISSUE THREAD

**Issue by matteotrubini** [gergo85/oc-news#62]
https://github.com/gergo85/oc-news/blob/ddc309e0a457c3e7a84b028efdd0e15ab6fb35b9/models/Posts.php#L200-L211

Maybe `published_at` should be set `beforeSave()` to `now()` if `status = 1`?
Otherwise I doesn't imagine which can be the voluntary use of `status = 1 && published_at = null`

**Comment by gergo85** [comment]
Thank you for your advice again! I updated the plugin.
