### ISSUE TITLE
Failed to save an updated post

### ISSUE THREAD

**Issue by lethiandev** [gergo85/oc-news#66]
Hi, I've encountered another bug, OC won't save me an updated post, because field named `postinfo` doesn't exist in the `news_post` table. According to the [oc docs](https://octobercms.com/docs/backend/widgets#form-widget-save-data), I've found that formwidgets tries to save a data, but disabling the save feature works ok.

For now, I've solved the problem by adding these lines to PostInfo.php:
```php
    public function getSaveValue($value)
    {
        return \Backend\Classes\FormField::NO_SAVE_DATA;
    }
```

PHP: 7.1.19
OC build: 437

**Comment by gergo85** [comment]
Thank you for the solution! I updated the plugin.
