### ISSUE TITLE
How to count Posts for each Category...

### ISSUE THREAD

**Issue by Tetraneon** [gergo85/oc-news#67]
Hi,
Many thanks for your useful and great job !
To count how many Posts are in a Category with a simple {{ category.posts.count() }}, it would be useful to add this in your Categories model : 
`    public $hasMany = [
        'posts' => [
            'Indikator\News\Models\Posts',
            'key'      => 'category_id',
        ],
    ];`
For example, this information could be added in a badge class span in bootstrap...

**Comment by gergo85** [comment]
Hi,  
Thank you for your suggestion!  
I added this code for plugin. Please update it.
