### ISSUE TITLE
Subscription regisration doesnt work

### ISSUE THREAD

**Issue by lemirage** [gergo85/oc-news#7]
Hello,
1. your pre-made form not working / the button subscription do nothings  
2. on Enter it make an ajax error and nothink is save

have you some solutions ? 

Thanks 

lemirage
![capture d ecran 2015-09-28 a 16 05 12](https://cloud.githubusercontent.com/assets/1391449/10137643/d87da6b6-65fa-11e5-834e-a3ac59c4ae95.png)
![capture d ecran 2015-09-28 a 16 05 23](https://cloud.githubusercontent.com/assets/1391449/10137645/db4fd652-65fa-11e5-97dd-825010ac5eec.png)

**Comment by gergo85** [comment]
I tested the form and it worked properly for me. Do you use the conponents of plugin or not?

Try to add the following php code to the page (where the form is location):
```
    function onSubscription()
    {
        $data = post();

        if (DB::table('news_subscribers')->where('email', $data['email'])->count() == 1) {
            return;
        }

        $rules = [
            'name'  => 'required|between:2,64',
            'email' => 'required|email|between:8,64'
        ];

        $validation = Validator::make($data, $rules);
        if ($validation->fails()) {
            throw new ValidationException($validation);
        }

        DB::table('news_subscribers')->insertGetId([
            'name' => $data['name'],
            'email' => $data['email'],
            'common' => '',
            'created' => 2,
            'statistics' => 0,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
    } 
```

**Comment by kuleyu** [comment]
Hello @gergo85 , I meet the same error. When i click the subscribe button, the throws a window says "AJAX handler 'onSubscription' was not found."

And i am sure that i have correctly used the the components of plugin, because other components of this plugin work well. 

I don't know how to solve it, and could you help me? 

Thanks!

**Comment by TimFoerster** [comment]
I guess your component is injected into a partial

**Comment by kuleyu** [comment]
Oh, it seems that i have found the reason. The problem above is because i used the subscription component in a partial file. When i use it in a page file, it works correctly.

**Comment by kuleyu** [comment]
@TimFoerster you are right! 😀

**Comment by kuleyu** [comment]
I have successfully used the subscription component in a partial file by using a indirect way:

component file:
```
{% put Subscription%}
............
code
............
{% endput %}
```

partial file:
```
{% component 'newsSubscribe' %}
{% placeholder Subscription%}
```

page file:
```
[newsSubscribe newsSubscribeLucky]
==
............
code
............
{% partial 'partial-file-name' %}
```
--------------------
So, we could try this method (just `Twig placeholder`) to put these components in partial file when using forms and frontend AJAX
