### ISSUE TITLE
E-mail confirmation always fails with charset set to uft8mb4 (MySQL, InnoDB).

### ISSUE THREAD

**Issue by gandafl** [gergo85/oc-news#71]
For mysql-databases with charset set to utf8mb4 and InnoDB-Engine the maximum size of VARCHAR is 191 characters. The ConfirmationHandler or the plugin installation does not account for this scenario.

Right now the ConfirmationHandler always creates a token with 255 characters. The token with 255 characters is send to the user, but only the first 191 characters are stored in the database so every e-mail confirmation will fail.

**Comment by gergo85** [comment]
Thank you for your feedback! I modified the plugin. Please update it.
