### ISSUE TITLE
Newsletters are not sending if no category selected

### ISSUE THREAD

**Issue by Andr1yk0** [gergo85/oc-news#73]
Hi. Thanks for the great plugin! 
I have a question.
In the edit subscriber form there is a hint below categories checkboxes with text "If no category is selected then the subscriber will receive the all newsletters." But when I have a new activated subscriber and no category selected newsletters is not sending to this subscriber. If any category selected everything works as expected. 
Looks like the problem is in NewsSender.php:
```
        if (Categories::count() > 0) {
            $activeSubscribers = $this->news->category->subscribers()->isSubscribed();
        }
```

**Comment by gergo85** [comment]
I modified this line. Please update the plugin!
