### ISSUE TITLE
[FR] Customize newsletter email content from online post

### ISSUE THREAD

**Issue by TimFoerster** [gergo85/oc-news#74]
I have the following feature request:

It should be possible to customize the newsletter email from the online post.
So that the newsletter email content is different to the online post (this one can be longer with more images etc.)

My idea would be to have another tab that shows a toggle switch and a richfield.
The toggle switch allows "enable custom newsletter email", or "override newsletter content".
The richfield shows the `post.newsletter_content` for the newsletter email.

In the mail template we check for `override_newsletter_content`, if that is set, we take the `post.newsletter_content` instead of the `post.content`.

@gergo85 Any suggestion or feedback? I would like to implement it till the end of the week.

**Comment by TimFoerster** [comment]
any update on that?

**Comment by gergo85** [comment]
Sorry for delay. I updated the plugin!
