### ISSUE TITLE
[Feature] Add tags for posts

### ISSUE THREAD

**Issue by Fenn-CS** [gergo85/oc-news#87]
Since this plugin supports just a single category for each posts (which I strongly encourage) I think it makes sense for us to add tags!

**Comment by gergo85** [comment]
I added this idea to my todo list.

**Comment by Fenn-CS** [comment]
Great then!

**Comment by gergo85** [comment]
I made this feature. Please update the plugin.

**Comment by hibangmike** [comment]
Hi @gergo85 ,

Thank you for this feature, but I can't figure it out how to get the links for tags ? and how to sort  and display tags when it is click ?
`  
            {% for tag in post.tags %}
            <a href="{{ 'blog'|page }}/tag/{{ tag }}">{{ tag }}</a>
            {% endfor %}
     `

Because there is no components for tag and would like to list all the tags and sort them.

Any help is appreciated.

Thank you

**Comment by hibangmike** [comment]
Thanks @gergo85 it's working great !

Just one issue with sorting on PHP 8, it doesn't work. It always set to ascending, can you help ?

Thank you

**Comment by gergo85** [comment]
It is a bug on PHP 8. I haven't been tested the plugin on PHP 8 and October CMS 2/3.
