### ISSUE TITLE
Problem with Show only translated posts

### ISSUE THREAD

**Issue by alescurk** [gergo85/oc-news#89]
I found a problem with using option "Show only translated posts"

Problem exists inplugins/indikator/news/models/Posts.php line 256

I have replaced line 256 with

$ids = Db::table('rainlab_translate_attributes')->where('model_type', 'Indikator\News\Models\Posts')->where('locale', $current_locale)->where('attribute_data', 'not like', '%"title":""%')->pluck('model_id');

Now it is working

**Comment by gergo85** [comment]
Do you use the latest version of October and the plugin?

**Comment by alescurk** [comment]
I was not but now I have updated with latest changes (also news module) but the problem is the same

After upgrade problematic line is 270

**Comment by gergo85** [comment]
Thank you for your report! I fixed this issue.
