### ISSUE TITLE
JS Error: Uncaught Error: Trigger action is not specified.

### ISSUE THREAD

**Issue by tinchoz49** [gergo85/oc-news#9]
Hi,

In the backend of your plugin i'm getting the next JS error: 

Uncaught Error: Trigger action is not specified in storm-min.js?v306:2882

Current build: 306
Great plugin by the way :+1:

**Comment by gergo85** [comment]
Thank you for reporting this issue! I fixed it and I updated the plugin.

**Comment by tinchoz49** [comment]
thanks @gergo85 !
