### ISSUE TITLE
Error on settings page with php 7.2, fresh installation

### ISSUE THREAD

**Issue by TimFoerster** [gergo85/oc-news#92]
```
substr() expects parameter 1 to be string, array given" on line 469 of [...]/vendor/laravel/framework/src/Illuminate/Support/Str.php
```

**Comment by gergo85** [comment]
Thank you for report this error! Please write more information about issue.

**Comment by TimFoerster** [comment]
1. Default array value doesnt work with checkboxlist
2. Why should be post in draft status be visible in the frontend, by default?

**Comment by gergo85** [comment]
The draft posts only show for logged admin users.

**Comment by TimFoerster** [comment]
k, good to know. But default array value doesnt work.

**Comment by TimFoerster** [comment]
but maybe this get fixed by https://github.com/octobercms/october/pull/4062
