### ISSUE TITLE
Error on /backend/system/settings/update/indikator/news/settings

### ISSUE THREAD

**Issue by AdrienAdB** [gergo85/oc-news#96]
After a new install from market place, settings has error as follow:
`substr() expects parameter 1 to be string, array given`

* Nothing in October Events log
* Plugin version 1.10.9
* OctoberCMS build 446
* PHP 7.2

**Comment by gergo85** [comment]
See this topic: https://octobercms.com/plugin/support/indikator-news/what-is-this-error-message-mean

**Comment by AdrienAdB** [comment]
Thanks, problem solved.
