### ISSUE TITLE
column category_id cannot be null

### ISSUE THREAD

**Issue by jonnydevv** [gergo85/oc-news#99]
If no category selected upon post creation, i get null error:

"SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'category_id' cannot be null (SQL: insert into `indikator_news_posts` (`user_id`, `title`, `slug`, `introductory`, `content`, `image`, `published_at`, `status`, `featured`, `category_id`, `tags`, `updated_at`, `created_at`) values (1, Workshop “Projeto Piloto Agroalimentar”, workshop-projeto-piloto-agroalimentar, , , , , 3, 2, , , 2019-02-18 11:51:01, 2019-02-18 11:51:01))" on line 664 of /var/www/october/vendor/laravel/framework/src/Illuminate/Database/Connection.php

I tried setting category in  posts/field.yaml as required but still get the same error.
<img width="504" alt="screenshot 2019-02-18 at 10 59 11" src="https://user-images.githubusercontent.com/2188826/52949640-637afd80-336c-11e9-8923-ceb14409d08d.png">

**Comment by gergo85** [comment]
Thank you for report this issue! I fixed it. Please force update the plugin.
